name: ballotify
description: "Online voting system for the 21st century"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6  # Check pub.dev for the latest version
  local_auth_windows: ^1.0.0  # For Windows Hello support
  google_fonts: ^6.1.0
  loading_animations: ^2.2.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0  # Add this line for carousel slider
  http: ^1.3.0
  connectivity_plus: ^6.1.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/candidate_img/
    - assets/fonts/
    - assets/certificate/
    - assets/

  fonts:
    - family: DS-Digital
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF